- hosts: all
  gather_facts: false
  vars:
    node_env: production
    local_dir: "{{ playbook_dir }}/../.."
  vars_files:
    - vars/secrets.yaml
    - vars/garzon.yaml
  roles:
    - docker-networks
    - website-frontend
  become: true
