/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "unknown_error": string;
        "invalid_token": string;
        "user_events_fetch_error": string;
        "verify_code_not_found": string;
        "invalid_verify_code": string;
    };
    "general": {
        "token_retrieved": string;
    };
    "validation": {
        "invalid_field": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
