- name: "server : create www dir"
  ansible.builtin.file:
    path: "{{ www_dir }}"
    owner: "{{ user_admin }}"
    mode: "{{ permission_dir }}"
    state: directory
  become: true

- name: "server : create project dir"
  ansible.builtin.file:
    path: "{{ garzon_root }}"
    owner: "{{ user_admin }}"
    mode: "{{ permission_dir }}"
    state: directory
  become: true

